import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_PATH = path.resolve(__dirname, "..", "data", "patients.json");

type Report = { text: string; timestamp: string };
type FeedbackSender = "patient" | "doctor";
type FeedbackMessage = Report & { sender?: FeedbackSender };

export type Analysis = {
  isSafe: boolean;
  interactions: Array<{
    medications: [string, string];
    severity: "minor" | "moderate" | "major" | "contraindicated";
    reason: string;
    canSeparateBySchedule: boolean;
    minHoursApart?: number;
  }>;
  recommendations: Array<{
    type: "keep_and_separate" | "replace_medication" | "avoid_combination";
    title: string;
    details: string;
  }>;
  schedule: Array<{
    medication: string;
    times: string[];
    note?: string;
  }>;
};

export type Patient = {
  id: string;
  name: string;
  labels?: string[];
  reports: Report[];
  medications?: any[];
  condition?: string; // Set by doctor
  analysis?: Analysis; // Generated by AI after doctor sets condition
  feedback?: FeedbackMessage[]; // Patient/doctor conversation about medications
  createdAt: string;
};

type DBShape = { patients: Patient[] };

function ensureDbFile() {
  const dir = path.dirname(DB_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(DB_PATH)) {
    fs.writeFileSync(DB_PATH, JSON.stringify({ patients: [] }));
  }
}

function readDb(): DBShape {
  ensureDbFile();
  const raw = fs.readFileSync(DB_PATH, "utf8");
  try {
    return JSON.parse(raw) as DBShape;
  } catch {
    return { patients: [] };
  }
}

function writeDb(db: DBShape) {
  ensureDbFile();
  fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2));
}

export function listPatients(): Patient[] {
  return readDb().patients;
}

export function getPatient(id: string): Patient | undefined {
  return readDb().patients.find((p) => p.id === id);
}

export function addPatient(patient: Patient) {
  const db = readDb();
  db.patients.push(patient);
  writeDb(db);
}

export function deletePatient(id: string): boolean {
  const db = readDb();
  const before = db.patients.length;
  db.patients = db.patients.filter((p) => p.id !== id);
  writeDb(db);
  return db.patients.length < before;
}

export function addReport(id: string, text: string) {
  const db = readDb();
  const p = db.patients.find((x) => x.id === id);
  if (!p) return false;
  p.reports.push({ text, timestamp: new Date().toISOString() });
  writeDb(db);
  return true;
}

export function setLabels(id: string, labels: string[]) {
  const db = readDb();
  const p = db.patients.find((x) => x.id === id);
  if (!p) return false;
  p.labels = labels;
  writeDb(db);
  return true;
}

export function setCondition(id: string, condition: string) {
  const db = readDb();
  const p = db.patients.find((x) => x.id === id);
  if (!p) return false;
  p.condition = condition;
  writeDb(db);
  return true;
}

export function setAnalysis(id: string, analysis: Analysis) {
  const db = readDb();
  const p = db.patients.find((x) => x.id === id);
  if (!p) return false;
  p.analysis = analysis;
  p.medications = analysis.schedule.map((s) => ({
    name: s.medication,
    dose: "per schedule",
    frequencyPerDay: 1,
  }));
  writeDb(db);
  return true;
}

export function addFeedback(
  id: string,
  text: string,
  sender: FeedbackSender = "patient",
) {
  const db = readDb();
  const p = db.patients.find((x) => x.id === id);
  if (!p) return false;
  if (!p.feedback) p.feedback = [];
  p.feedback.push({ text, timestamp: new Date().toISOString(), sender });
  writeDb(db);
  return true;
}
